### ISSUE TITLE
MUTAG labels

### ISSUE THREAD

**Issue by alirezadizaji** [flyingdoog/PGExplainer#11]
Hi,
The 2210th graph has label zero (mutagen) but it has neither of NO2 nor NH2. Is there something that I am missing? 
thanks

![Figure_11](https://user-images.githubusercontent.com/33565522/186670489-d8eadfb3-5413-4e47-961d-058d2484a837.png)

**Comment by alirezadizaji** [comment]
There are several other graph samples having neither NO2 nor NH2 but labeled as zero.

**Comment by flyingdoog** [comment]
Hi,

That is reasonable.   Mutag dataset is complex.  Mutagen can be caused by different reasons   No2 and nh2 are just two possible reasons.  We describe how to pre-process the dataset in detail in our paper.

Best,
Dongsheng
________________________________

**Comment by alirezadizaji** [comment]
I understood because the paper mentioned that carbon ring with NO2 or NH2 causes mutagenic effect. Just to make sure I have found a graph that I mentioned in this [issue](https://github.com/flyingdoog/PGExplainer/issues/12#issuecomment-1227338692) (checkout the image) that it has NH2 but it is labeled as non-mutagen. Is this ok?

**Comment by flyingdoog** [comment]
thats also possible

Best,
Dongsheng
________________________________

**Comment by alirezadizaji** [comment]
Thanks
