### ISSUE TITLE
About the readout operation in graph classification

### ISSUE THREAD

**Issue by Radical3-HeZhang** [flyingdoog/PGExplainer#6]
Dear author, 

I hit upon that it seems like the global pooling operation in graph classification is on the wrong axis. For example, when reading out the "out" ( graph_num, node_size, fea_num) with axis=-1, the resulting shape is (graph_num, node_size) but not the desired (graph_num, fea_num).

**Comment by flyingdoog** [comment]
Thanks for report the bug.  I have fixed it and will update the explamlar usage later.

**Comment by Radical3-HeZhang** [comment]
The BA-2motifs.ipynb seems like unavailable now. The modification from axis=-1 to axis=1 raises new ValueError: Tensor's shape (50, 2) is not compatible with supplied shape [40, 2].

**Comment by flyingdoog** [comment]
Just delete the saved GNN model and re-run the train-BA-2motifs to get an updated GNN model for the explanation.

**Comment by Radical3-HeZhang** [comment]
re-run the train_BA-2motif seems don't work well in acc items ![image](https://user-images.githubusercontent.com/64715540/117602823-f1816f80-b194-11eb-96d3-5e8ad78e93ca.png)

**Comment by Radical3-HeZhang** [comment]
> I have fixed it, please refer to the updated train_BA-2motifs and BA-2motifs.
> 
> The reason is that the early_stop should be large in order to get an accurate GNN model.
> 
> I am now working on the MUTAG dataset and will update it later.

Thanks for the quick reply. But it seems like the BA-2motifs don't work well in terms of AUC after the modification. 
![image](https://user-images.githubusercontent.com/64715540/117605106-4f648600-b19a-11eb-8694-85a9709e5b5a.png)

**Comment by flyingdoog** [comment]
Did you delete the saved checkpoint file and re-run both train-BA-2motifs and BA-2motifs?
I have updated my results in BA-2motifs.ipynb and it's correct.

**Comment by Radical3-HeZhang** [comment]
I just re-download the whole code and try to reproduce the result. Did you have finished the update of BA-2motifs? It seems like it is the BA-2motif but not BA-2motifs is updated.
![image](https://user-images.githubusercontent.com/64715540/117605902-17f6d900-b19c-11eb-89e1-d4577909faa2.png)
And I also find the error below then run BA-2motif in cell 9
![image](https://user-images.githubusercontent.com/64715540/117606225-c69b1980-b19c-11eb-973a-5ece3a5742f2.png)

**Comment by flyingdoog** [comment]
Sorry for the late response late.   I have fixed it and upload the files.  
Actually, you can just delete ori_pred in line 18 and it will work.

**Comment by flyingdoog** [comment]
Since this issue has been solved, I will close it.  Any comments are welcomed.
