### ISSUE TITLE
About the number of samples K in the paper.

### ISSUE THREAD

**Issue by xugangwu95** [flyingdoog/PGExplainer#7]
Hi,

Really cool project. When I compared this implementation with the one decribed in the paper, I found out that this code does not sample K times for each node's subgraph. Is there any reason for it and will it leads to a high variance for a certain node?

Looking forward to your response!

Thanks!

**Comment by flyingdoog** [comment]
We just set k=1 due to its empirically good performance.  Theoretically large k leads to smaller variance although we didn’t empirically verify it.
