### ISSUE TITLE
The loss in the code is not the same as in the paper

### ISSUE THREAD

**Issue by hcn323** [flyingdoog/PGExplainer#8]
the loss in the paper is:
![image](https://user-images.githubusercontent.com/32607340/143240277-be406891-788a-4cc1-89d6-fecbe6b260eb.png)
but in code:
![image](https://user-images.githubusercontent.com/32607340/143240883-9cb987fc-1876-44f2-8c76-4419c1566f37.png)
you just take out the probability of the item corresponding to the label,and use -tf.math.log() to get the pred_loss,$\sum_{c=1}^C$ I don't think it shows up in code.

**Comment by flyingdoog** [comment]
Other cases of c are 0.  Please refer to the implementation of cross entropy.
